# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - tipatzahav-backend # ודא שהשם כאן תואם לשם ה-App Service שלך

on:
  push:
    branches:
      - main # או master, לפי הענף הראשי שלך
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # השתמש בגרסה עדכנית

      - name: Set up Node.js version
        uses: actions/setup-node@v4 # השתמש בגרסה עדכנית
        with:
          node-version: '18.x' # או הגרסה שבחרת ב-App Service

      - name: List files in the checkout directory # שלב בדיקה חדש
        run: ls -la # פקודה שמציגה את כל הקבצים והתיקיות

      - name: Install dependencies in backend folder
        run: npm install
        working-directory: backend # 2 רווחים לפני working-directory

      # אם יש לך שלב build ב-backend (נדיר, אבל אם כן תוסיף כאן)
      # - name: Build backend (if needed)
      #   run: npm run build --if-present
      #   working-directory: backend # שים לב להזחה גם פה אם תוסיף

      # שלב העלאה ל-Azure
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp # הוספנו ID לשלב
        uses: azure/webapps-deploy@v3 # השתמש בגרסה עדכנית
        with:
          app-name: 'tipatzahav-backend' # <<< ודא שזה שם ה-App Service שיצרת
          slot-name: 'Production' # בדרך כלל production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EXAMPLE }} # <<< חשוב מאוד: השם כאן חייב להיות **זהה** לשם ה-Secret ש-Azure יצר ב-GitHub (בדוק בהגדרות -> Secrets -> Actions)
          package: . # מעלים את כל ה-repository (ופקודת ה-startup תטפל בתיקייה)
